name: SSH Deploy

on:
  push:
    branches:
      - master
      - new-ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: cd web_ui && yarn install

    - name: Build the React app
      run: |
        cd web_ui && VITE_API_BASE_URL=${{ secrets.API_BASE_URL }} \
        VITE_API_BASE_URL_WS=${{ secrets.API_BASE_URL_WS }} \
        VITE_ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} \
        yarn vite build --base=/static/

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        overwrite: 1
        strip_components: 3
        source: './web_ui/dist/'
        target: '~/hubase/hubase/front/'

    - name: Execute remote commands via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/hubase/hubase;
          git pull;
          source venv/bin/activate;
          pip install -r requirements.txt;
          cd src;
          sudo kill $(pgrep python);
          nohup sudo env "PATH=$PATH" python __main__.py > nohup.out 2> nohup.err < /dev/null &
